spring:
  security:
    user:
      name: conquer
      password: conquer
  profiles:
    active: development
  application:
    name: teams-api
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    mysql:
      url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SCHEMA:franchise}?zeroDateTimeBehavior=convertToNull&useTimezone=true&serverTimezone=UTC
      username: ${DB_USER:root}
      password: ${DB_PASS:}
      hikari:
        pool-name: franchise
        minimum-idle: 1
        maximum-pool-size: 3
    postgres:
      url: jdbc:postgresql://${DB_PG_HOST:localhost}:${DB_PG_PORT:5432}/${DB_PG_SCHEMA:shuri}
      username: ${DB_PG_USER:postgres}
      password: ${DB_PG_PASS:admin}
      hikari:
        pool-name: shuri
        minimum-idle: 1
        maximum-pool-size: 3
  data:
    mongodb:
      uri: mongodb://localhost:27017/teams
  main:
    allow-circular-references: true
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    defaults:
      enabled: true
feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000
        loggerLevel: basic
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

---
spring:
  config:
    activate:
      on-profile: development
  data:
    mongodb:
      uri: mongodb://localhost:27017/teams
logging:
  level:
    br.com.conquer: debug
server:
  port: ${PORT:8888}
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always
swagger:
  server:
    url: http://localhost:8888
springdoc:
  swagger-ui:
    path: /teams-api/swag
  api-docs:
    path: /teams-api/api-docs

---
spring:
  config:
    activate:
      on-profile: homolog
logging:
  level:
    br.com.conquer: DEBUG
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
swagger:
  server:
    url: http://teams-api:8080/
springdoc:
  swagger-ui:
    path: /teams-api/swag
  api-docs:
    path: /teams-api/api-docs

---
spring:
  config:
    activate:
      on-profile: production
logging:
  level:
    br.com.conquer: DEBUG
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
swagger:
  server:
    url: http://teams-api:8080/
springdoc:
  swagger-ui:
    path: /teams-api/swag
  api-docs:
    path: /teams-api/api-docs